### ISSUE TITLE
Need upgrade project to support dart 2

### ISSUE THREAD

**Issue by Moanrisy** [hathibelagal/CandyLauncher#1]
Running "flutter packages get" in CandyLauncher...              
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because candy requires SDK version >=1.19.0 <2.0.0, version solving failed.

**Comment by ac130kz** [comment]
@iNyamuk launcher_assist package is limited to SDK version >=1.19.0 <2.0.0, 

https://pub.dartlang.org/packages/launcher_assist#-analysis-tab-

PS found a solution (https://github.com/flutter/flutter/issues/22031): 
* download latest launcher_assist from the link above
* update pubspec.yaml with the following:
```
environment:
  sdk: '>=2.0.0 <3.0.0'
```
* update example/android/build.gradle with:
```
        classpath 'com.android.tools.build:gradle:3.2.1'
```
* update example/android/gradle/wrapper/gradle-wrapper.properties with:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.3-all.zip
```

UPDATE: I've created a fully working fork https://github.com/ac130kz/CandyLauncher

**Comment by iNyamuk** [comment]
@ac130kz Thanks for creating fork that worked but I have another problem,
when i run this command on terminal 'flutter run'
it stuck on 'Initializing gradle'

command 'flutter run' work fine in other flutter project,
do you have any idea why this is happen?
